"""Added email column to users table

Revision ID: 170b2464a612
Revises: 4dddc6dc1ff6
Create Date: 2020-11-16 21:18:30.234184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "170b2464a612"
down_revision = "4dddc6dc1ff6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=80), nullable=False))
    op.create_unique_constraint("users_email_key", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
